[app]
name = "hwww"
website = "https://hwww.org"
resume = "https://resume.hwww.org/cv"
artworks = "https://artworks.hwww.org/index.json"
repository = "https://github.com/4www/megui"
default_theme = "auto"  # Options: "auto", "dark", "light"
